title: Reagan's Homepage
page-top-title: Reagan
top-section-bg-text: Finance
home-subtitle: Reagan&ensp;|&ensp;李根
nav-home: HOME
nav-experience: EXPERIENCE
nav-projects: PROJECTS
nav-awards: AWARDS
nav-menu-text: MENU
experience-subtitle: <i class="bi bi-briefcase-fill"></i>&nbsp;EXPERIENCE
projects-subtitle: <i class="bi bi-file-text-fill"></i>&nbsp;PROJECTS
awards-subtitle: <i class="bi bi-award-fill"></i>&nbsp;AWARDS
copyright-text: '&copy; Reagan 2025-2026. All Rights Reserved.'
license-link: License
